services:
  - type: web
    name: protweaks-server
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: DOMAIN
        value: https://e-protweaks.online
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://e-protweaks.online
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true